# Generated by Django 3.0.6 on 2020-05-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oneevent", "0007_auto_20151212_1805"),
    ]

    operations = [
        migrations.DeleteModel(name="Message",),
    ]
