# Generated by Django 3.0.6 on 2020-05-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oneevent", "0009_event_timezone"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="city",),
    ]
